### ISSUE TITLE
The script queries a different url than the one provided, resulting in "Nothing to download"

### ISSUE THREAD

**Issue by nuanjanP** [bitdruid/python-wayback-machine-downloader#16]
**Describe**
The script queries a different url than the one provided, resulting in "Nothing to download"

**Snapshot to reproduce**

**Command to reproduce**
`waybackup -u http://hyaku-lab.net/?page_id=582 -f`

**Terminal output**
```
Querying snapshots...
---> hyaku-lab.net/%3fpage_id%3d582/*

-----> 0 snapshots to utilize

Nothing to download
```

**Additional context**
There are clearly snapshots on the [Wayback Machine site](http://web.archive.org/web/20130315000000*/http://hyaku-lab.net/?page_id=582) but the script seems to pad `/*` to the url provided (`http://hyaku-lab.net/?page_id=582`), resulting in querying for a nonexistent url.

I've tried using the `-e` flag to download the explicit given url, but it doesn't work either. The script is still querying for `hyaku-lab.net/%3fpage_id%3d582/*`.

**Comment by nuanjanP** [comment]
Yes, I am on Windows 10. Sorry for forgetting to mentioning ^_^"

**Comment by bitdruid** [comment]
please take your time and review commit 2fdd850b27d445558a76027659a3d4ce57981fcd if this resolves your issue

**Comment by nuanjanP** [comment]
> please take your time and review commit [2fdd850](https://github.com/bitdruid/python-wayback-machine-downloader/commit/2fdd850b27d445558a76027659a3d4ce57981fcd) if this resolves your issue

Thank you for the swift response. Now the following command downloads the 2 snapshots available as shown in [Wayback Machine's page](http://web.archive.org/web/20130315000000*/http://hyaku-lab.net/?page_id=582)

```
waybackup -u http://hyaku-lab.net/?page_id=582 -f --explicit
```

with the terminal response being this:

```
Querying snapshots...
---> hyaku-lab.net/%3fpage_id%3d582

-----> 3 snapshots to utilize

Downloading snapshots...

-----> Snapshots prepared

-----> Starting worker: 1

-----> Attempt: [1/1] Snapshot [1/3] - Worker: 1
UNEXPECTED -> HTTP: 404 - Not Found
           -> URL: https://web.archive.org/web/20221211005240id_/http://hyaku-lab.net/?page_id=582       

-----> Attempt: [1/1] Snapshot [2/3] - Worker: 1
SUCCESS    -> HTTP: 200 - OK
           -> URL: https://web.archive.org/web/20130922121235id_/http://hyaku-lab.net/?page_id=582       
           -> FILE: C:\a\waybackup_snapshots\hyaku-lab.net\20130922121235\%3fpage_id%3d582

-----> Attempt: [1/1] Snapshot [3/3] - Worker: 1
SUCCESS    -> HTTP: 200 - OK
           -> URL: https://web.archive.org/web/20130530172708id_/http://hyaku-lab.net/?page_id=582       
           -> FILE: C:\a\waybackup_snapshots\hyaku-lab.net\20130530172708\%3fpage_id%3d582

Files downloaded: 2
Not downloaded: 1
```

But I still have a few questions if I may:

- Can the saved file be automatically configured to have the `.htm` extension? (This can be fixed on my end, but, just asking.)
- (The bigger question) I apologize if I misunderstood how this library works, but when I download pages with images in them like in this case, are the images also saved from Wayback Machine's archive? Because at the moment, only 2 html files are downloaded (corresponding to the 2 snapshots), while the images inside are still linking to the original site (not Wayback's copy).

I hope my response isn't too much trouble ^_^"

**Comment by bitdruid** [comment]
for your first one:
i'm currently not sure about adding .html extensions to query-strings as they are not a separate file in the original context but i'm open for any discussion about that

your second:
when you request the url `http://hyaku-lab.net/?page_id=582` it is looking for a snapshot of that explicit url. this does not include any other files. so if you want to get the ressources as well you have to query a path instead of a file/query string. the tool will download all snapshots of individual files that match that path. you could also request snapshots of logo.png and this should never give you any css or js ressources from the page as you don't want that kind of stuff. just your requested file.

so in your example just use that one:

`waybackup -u http://hyaku-lab.net -c --worker 4 --auto`

there are about 362 downloadable files and will rebuild the website inside your output-folder. (including ressources)

**Comment by nuanjanP** [comment]
Thank you very much for your answer :)
